exports.fakeData = function(callback) {
  var masterlist = { name: 'newsfeed',
      size: 111,
      mentions: 0,
      children:
       [ { name: 'Nathaniel Rich', size: 0, children: [] },
         { name: 'Ethan Wragge', size: 0, children: [] },
         { name: 'Creighton', size: 0, children: [] },
         { name: 'Doug McDermott', size: 0, children: [] },
         { name: 'Big East', size: 0, children: [] },
         { name: 'Prime Minister Najib Razak', size: 0, children: [] },
         { name: 'Prime Minister Najib Razak', size: 0, children: [] },
         { name: 'Malaysia', size: 0, children: [] },
         { name: 'Malaysia Airlines Flight', size: 0, children: [] },
         { name: 'PBOC', size: 0, children: [] },
         { name: 'Bank of China', size: 0, children: [] },
         { name: 'president', size: 0, children: [] },
         { name: 'Prime Minister Enda Kenny', size: 0, children: [] },
         { name: 'St. Patrick', size: 0, children: [] },
         { name: 'Henrik Lundqvist', size: 0, children: [] },
         { name: 'Mike Richter', size: 0, children: [] },
         { name: 'Rangers', size: 0, children: [] },
         { name: 'Carl Hagelin', size: 0, children: [] },
         { name: 'Winnipeg', size: 0, children: [] },
         { name: 'Ed Cooley', size: 0, children: [] },
         { name: 'Friars', size: 0, children: [] },
         { name: 'Seton Hall', size: 0, children: [] },
         { name: 'Big East', size: 0, children: [] },
         { name: 'Friars', size: 0, children: [] },
         { name: 'Seton Hall', size: 0, children: [] },
         { name: 'Big East', size: 0, children: [] },
         { name: 'Office of Naval Intelligence', size: 0, children: [] },
         { name: 'Paul George', size: 0, children: [] },
         { name: 'David West', size: 0, children: [] },
         { name: 'Indiana Pacers', size: 0, children: [] },
         { name: 'Philadelphia', size: 0, children: [] },
         { name: 'rape', size: 0, children: [] },
         { name: 'New York high school', size: 0, children: [] },
         { name: 'New Jersey', size: 0, children: [] },
         { name: 'Anne Frank', size: 0, children: [] },
         { name: 'Tokyo', size: 0, children: [] },
         { name: 'explosive device', size: 0, children: [] },
         { name: 'Israeli Army', size: 0, children: [] },
         { name: 'Israeli military', size: 0, children: [] },
         { name: 'Nicklas Backstrom', size: 0, children: [] },
         { name: 'Mrs. Brubeck', size: 0, children: [] },
         { name: 'Mr. Thomas', size: 0, children: [] },
         { name: 'Hollywood', size: 0, children: [] },
         { name: 'The Associated Press', size: 0, children: [] },
         { name: 'Zack Wheeler', size: 0, children: [] },
         { name: 'Jarrod Saltalamacchia', size: 0, children: [] },
         { name: 'Mets', size: 0, children: [] },
         { name: 'Miami Marlins', size: 0, children: [] },
         { name: 'Fla', size: 0, children: [] },
         { name: 'Robert Garrigus', size: 0, children: [] },
         { name: 'Palm Harbor', size: 0, children: [] },
         { name: 'Fla', size: 0, children: [] },
         { name: 'Devyani Khobragade', size: 0, children: [] },
         { name: 'visa fraud', size: 0, children: [] },
         { name: 'Indianapolis Colts', size: 0, children: [] },
         { name: 'Hakeem Nicks', size: 0, children: [] },
         { name: 'Jim Irsay', size: 0, children: [] },
         { name: 'Twitter', size: 0, children: [] },
         { name: 'Steve Smith', size: 0, children: [] },
         { name: 'Baltimore Ravens', size: 0, children: [] },
         { name: 'Joe Flacco', size: 0, children: [] },
         { name: 'Novak Djokovic', size: 0, children: [] },
         { name: 'Julien Benneteau', size: 0, children: [] },
         { name: 'Indian Wells', size: 0, children: [] },
         { name: 'Calif', size: 0, children: [] },
         { name: 'BNP', size: 0, children: [] },
         { name: 'Mr. Kinzler', size: 0, children: [] },
         { name: 'NASA', size: 0, children: [] },
         { name: 'Mr. Fix-It', size: 0, children: [] },
         { name: 'United States', size: 0, children: [] },
         { name: 'World Cup', size: 0, children: [] },
         { name: 'Pascal Simbikangwa', size: 0, children: [] },
         { name: 'officer', size: 0, children: [] },
         { name: 'France', size: 0, children: [] },
         { name: 'Lakhdar Brahimi', size: 0, children: [] },
         { name: 'United Nations', size: 0, children: [] },
         { name: 'Tehran', size: 0, children: [] },
         { name: 'Iran', size: 0, children: [] },
         { name: 'Syria', size: 0, children: [] },
         { name: 'Carl Hagelin', size: 0, children: [] },
         { name: 'Rangers', size: 0, children: [] },
         { name: 'Obama administration', size: 0, children: [] },
         { name: 'East Harlem', size: 0, children: [] },
         { name: 'New York City', size: 0, children: [] },
         { name: 'iPad', size: 0, children: [] },
         { name: 'Yankees', size: 0, children: [] },
         { name: 'Ed Sessa', size: 0, children: [] },
         { name: 'Harlem', size: 0, children: [] },
         { name: 'S. T. Joshi', size: 0, children: [] },
         { name: 'Michael R. Bloomberg', size: 0, children: [] },
         { name: 'Bill de Blasio', size: 0, children: [] },
         { name: 'St. Patrick', size: 0, children: [] },
         { name: 'Katie Couric', size: 0, children: [] },
         { name: 'Kiev', size: 0, children: [] },
         { name: 'Ukraine', size: 0, children: [] },
         { name: 'Russia', size: 0, children: [] },
         { name: 'Washington', size: 0, children: [] },
         { name: 'marijuana', size: 0, children: [] },
         { name: 'Sulaiman Abu Ghaith', size: 0, children: [] },
         { name: 'New York', size: 0, children: [] },
         { name: 'New Jersey', size: 0, children: [] },
         { name: 'Connecticut', size: 0, children: [] },
         { name: 'president', size: 0, children: [] },
         { name: 'immigration law', size: 0, children: [] },
         { name: 'Brussels', size: 0, children: [] },
         { name: 'Chanel', size: 0, children: [] },
         { name: 'Indiana', size: 0, children: [] },
         { name: 'basketball', size: 0, children: [] },
         { name: 'Kevin McCrary', size: 0, children: [] },
         { name: 'Manhattan', size: 0, children: [] },
         { name: 'Chanel', size: 0, children: [] } ],
      keywords:
       [ 'Nathaniel Rich',
         'Ethan Wragge',
         'Creighton',
         'Doug McDermott',
         'Big East',
         'Prime Minister Najib Razak',
         'Prime Minister Najib Razak',
         'Malaysia',
         'Malaysia Airlines Flight',
         'PBOC',
         'Bank of China',
         'president',
         'Prime Minister Enda Kenny',
         'St. Patrick',
         'Henrik Lundqvist',
         'Mike Richter',
         'Rangers',
         'Carl Hagelin',
         'Winnipeg',
         'Ed Cooley',
         'Friars',
         'Seton Hall',
         'Big East',
         'Friars',
         'Seton Hall',
         'Big East',
         'Office of Naval Intelligence',
         'Paul George',
         'David West',
         'Indiana Pacers',
         'Philadelphia',
         'rape',
         'New York high school',
         'New Jersey',
         'Anne Frank',
         'Tokyo',
         'explosive device',
         'Israeli Army',
         'Israeli military',
         'Nicklas Backstrom',
         'Mrs. Brubeck',
         'Mr. Thomas',
         'Hollywood',
         'The Associated Press',
         'Zack Wheeler',
         'Jarrod Saltalamacchia',
         'Mets',
         'Miami Marlins',
         'Fla',
         'Robert Garrigus',
         'Palm Harbor',
         'Fla',
         'Devyani Khobragade',
         'visa fraud',
         'Indianapolis Colts',
         'Hakeem Nicks',
         'Jim Irsay',
         'Twitter',
         'Steve Smith',
         'Baltimore Ravens',
         'Joe Flacco',
         'Novak Djokovic',
         'Julien Benneteau',
         'Indian Wells',
         'Calif',
         'BNP',
         'Mr. Kinzler',
         'NASA',
         'Mr. Fix-It',
         'United States',
         'World Cup',
         'Pascal Simbikangwa',
         'officer',
         'France',
         'Lakhdar Brahimi',
         'United Nations',
         'Tehran',
         'Iran',
         'Syria',
         'Carl Hagelin',
         'Rangers',
         'Obama administration',
         'East Harlem',
         'New York City',
         'iPad',
         'Yankees',
         'Ed Sessa',
         'Harlem',
         'S. T. Joshi',
         'Michael R. Bloomberg',
         'Bill de Blasio',
         'St. Patrick',
         'Katie Couric',
         'Kiev',
         'Ukraine',
         'Russia',
         'Washington',
         'marijuana',
         'Sulaiman Abu Ghaith',
         'New York',
         'New Jersey',
         'Connecticut',
         'president',
         'immigration law',
         'Brussels',
         'Chanel',
         'Indiana',
         'basketball',
         'Kevin McCrary',
         'Manhattan',
         'Chanel' ] }
  callback(masterlist);
};