{
  "status": "OK",
  "copyright": "Copyright (c) 2014 The New York Times Company.  All Rights Reserved.",
  "num_results": 57894,
  "results": [
    {
      "section": "Business Day",
      "subsection": "Dealbook",
      "title": "Chobani Said to Seek Investment That Would Value It at $5 Billion",
      "abstract": "Chobani, the fast-growing yogurt maker, is said to be in talks with six potential investors as it seeks more capital to expand internationally.",
      "url": "http://dealbook.nytimes.com/2014/03/11/chobani-said-to-seek-investment-that-would-value-it-at-5-billion/",
      "byline": "By WILLIAM ALDEN",
      "thumbnail_standard": "images/2014/03/12/business/dbpix-chobani/dbpix-chobani-thumbStandard.jpg",
      "item_type": "Blog",
      "source": "The New York Times",
      "updated_date": "2014-03-11T18:14:26-04:00",
      "created_date": "2014-03-11T18:14:27-04:00",
      "published_date": "2014-03-11T00:00:00-04:00",
      "material_type_facet": "News",
      "kicker": "DealBook",
      "subheadline": "",
      "des_facet": ["Factories and Manufacturing", "Yogurt"],
      "org_facet": ["Chobani Inc"],
      "per_facet": "",
      "geo_facet": "",
      "related_urls": [
        {
          "suggested_link_text": "Cameron Sees Technology as Unlikely Ally of Western Workers ",
          "url": "http://dealbook.nytimes.com/2014/01/24/cameron-sees-technology-as-western-workers-unlikely-ally/"
        },
        {
          "suggested_link_text": "Apprenticeships Could Help Reduce Youth Unemployment, Business Leaders Say",
          "url": "http://dealbook.nytimes.com/2014/01/23/apprenticeships-could-reduce-youth-unemployment-business-leaders-say/"
        }
      ],
      "blog_name": "DealBook",
      "multimedia": [
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/business/dbpix-chobani/dbpix-chobani-thumbStandard.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "",
          "copyright": ""
        }
      ]
    },
    {
      "section": "Business Day",
      "subsection": "Economy",
      "title": "A Relentless Rise in Unequal Wealth",
      "abstract": "The economic forces concentrating more and more wealth into the hands of the fortunate few are almost sure to prevail for a long time, according to a new book by the economist Thomas Piketty.",
      "url": "http://www.nytimes.com/2014/03/12/business/economy/a-relentless-rise-in-unequal-wealth.html",
      "byline": "By EDUARDO PORTER",
      "thumbnail_standard": "http://graphics8.nytimes.com/images/2012/02/29/business/eduardo-porter/eduardo-porter-thumbStandard-v6.jpg",
      "item_type": "Article",
      "source": "The New York Times",
      "updated_date": "2014-03-11T18:13:47-04:00",
      "created_date": "2014-03-11T18:11:34-04:00",
      "published_date": "2014-03-12T00:00:00-04:00",
      "material_type_facet": "News",
      "kicker": "Economic Scene",
      "subheadline": "",
      "des_facet": ["Income Inequality", "Economic Conditions and Trends", "Labor and Jobs", "Wages and Salaries"],
      "org_facet": "",
      "per_facet": "",
      "geo_facet": "",
      "related_urls": null,
      "multimedia": [
        {
          "url": "http://graphics8.nytimes.com/images/2012/02/29/business/eduardo-porter/eduardo-porter-thumbStandard-v6.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "Eduardo Porter",
          "copyright": "Earl Wilson/The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2012/02/29/business/eduardo-porter/eduardo-porter-articleInline-v3.jpg",
          "format": "Normal",
          "height": 285,
          "width": 190,
          "type": "image",
          "subtype": "photo",
          "caption": "Eduardo Porter",
          "copyright": "Earl Wilson/The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2012/02/29/business/eduardo-porter/eduardo-porter-thumbLarge-v5.jpg",
          "format": "thumbLarge",
          "height": 150,
          "width": 150,
          "type": "image",
          "subtype": "photo",
          "caption": "Eduardo Porter",
          "copyright": "Earl Wilson/The New York Times"
        }
      ]
    },
    {
      "section": "Arts",
      "subsection": "Music",
      "title": "Celebrating the Pianist Ursula Oppens at 70",
      "abstract": "“Happy Birthday, Ursula” featured four pianists at Symphony Space on Thursday, along with an appearance by the woman of the hour.",
      "url": "http://www.nytimes.com/2014/03/12/arts/music/happy-birthday-ursula-a-tribute-at-symphony-space.html",
      "byline": "By VIVIEN SCHWEITZER",
      "thumbnail_standard": "",
      "item_type": "Article",
      "source": "The New York Times",
      "updated_date": "2014-03-11T18:07:14-04:00",
      "created_date": "2014-03-11T18:07:16-04:00",
      "published_date": "2014-03-12T00:00:00-04:00",
      "material_type_facet": "Review",
      "kicker": "Music Review",
      "subheadline": "",
      "des_facet": ["Classical Music"],
      "org_facet": "",
      "per_facet": ["Oppens, Ursula"],
      "geo_facet": "",
      "related_urls": null,
      "multimedia": ""
    },
    {
      "section": "U.S.",
      "subsection": "",
      "title": "N.S.A. Memo Expands Access to FISA Information",
      "abstract": "In 2006, the National Security Agency sought to expand access to Foreign Intelligence Surveillance Act information to codebreakers around the country.",
      "url": "http://www.nytimes.com/interactive/2014/03/12/us/NSA-internal-access-memo.html",
      "byline": "By CHARLIE SAVAGE",
      "thumbnail_standard": "",
      "item_type": "Interactive",
      "source": "The New York Times",
      "updated_date": "2014-03-11T18:05:15-04:00",
      "created_date": "2014-03-11T18:05:16-04:00",
      "published_date": "2014-03-12T00:00:00-04:00",
      "material_type_facet": "",
      "kicker": "",
      "subheadline": "",
      "des_facet": ["Surveillance of Citizens by Government", "Foreign Intelligence Surveillance Act (FISA)"],
      "org_facet": ["National Security Agency"],
      "per_facet": "",
      "geo_facet": "",
      "related_urls": null,
      "multimedia": ""
    },
    {
      "section": "U.S.",
      "subsection": "",
      "title": "Ashcroft Memo on Intelligence Sharing Procedures",
      "abstract": "In August 2002, the attorney general issued new procedures that lowered safeguards on providing information about Americans to foreign governments that was deemed relevant to terrorism issues.",
      "url": "http://www.nytimes.com/interactive/2014/03/12/us/ashcroft-dissemination-doc.html",
      "byline": "By CHARLIE SAVAGE",
      "thumbnail_standard": "",
      "item_type": "Interactive",
      "source": "The New York Times",
      "updated_date": "2014-03-11T18:03:37-04:00",
      "created_date": "2014-03-11T18:03:37-04:00",
      "published_date": "2014-03-12T00:00:00-04:00",
      "material_type_facet": "",
      "kicker": "",
      "subheadline": "",
      "des_facet": ["Surveillance of Citizens by Government", "Foreign Intelligence Surveillance Act (FISA)"],
      "org_facet": ["National Security Agency"],
      "per_facet": ["Ashcroft, John"],
      "geo_facet": "",
      "related_urls": null,
      "multimedia": ""
    },
    {
      "section": "U.S.",
      "subsection": "",
      "title": "Classification Guide for FISA, the Protect America Act and the FISA Amendments Act",
      "abstract": "A guide to secrecy restrictions for various aspects of programs to spy on domestic soil for national security purposes.",
      "url": "http://www.nytimes.com/interactive/2014/03/12/us/fisa-classification-doc.html",
      "byline": "By CHARLIE SAVAGE",
      "thumbnail_standard": "",
      "item_type": "Interactive",
      "source": "The New York Times",
      "updated_date": "2014-03-11T18:01:35-04:00",
      "created_date": "2014-03-11T18:01:36-04:00",
      "published_date": "2014-03-12T00:00:00-04:00",
      "material_type_facet": "",
      "kicker": "",
      "subheadline": "",
      "des_facet": ["Foreign Intelligence Surveillance Act (FISA)", "Surveillance of Citizens by Government"],
      "org_facet": "",
      "per_facet": "",
      "geo_facet": "",
      "related_urls": null,
      "multimedia": ""
    },
    {
      "section": "Arts",
      "subsection": "Music",
      "title": "Offering Choral Solace for Composers’ Laments",
      "abstract": "The Choir of Trinity Wall Street opened a concert series based on works inspired by the Book of Lamentations.",
      "url": "http://www.nytimes.com/2014/03/12/arts/music/trinity-choir-performs-works-based-on-the-book-of-lamentations.html",
      "byline": "By STEVE SMITH",
      "thumbnail_standard": "http://graphics8.nytimes.com/images/2014/03/12/arts/12TRINITY/12TRINITY-thumbStandard.jpg",
      "item_type": "Article",
      "source": "The New York Times",
      "updated_date": "2014-03-11T18:00:29-04:00",
      "created_date": "2014-03-11T18:00:30-04:00",
      "published_date": "2014-03-12T00:00:00-04:00",
      "material_type_facet": "Review",
      "kicker": "Music Review",
      "subheadline": "",
      "des_facet": ["Music", "Classical Music"],
      "org_facet": ["Choir of Trinity Wall Street"],
      "per_facet": "",
      "geo_facet": "",
      "related_urls": null,
      "multimedia": [
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12TRINITY/12TRINITY-thumbStandard.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "<strong>Choir of Trinity Wall Street </strong> The ensemble performed on Sunday as part of Trinity Church&rsquo;s Lamentatio concert series in Lower Manhattan.",
          "copyright": "Tina Fineberg for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12TRINITY/12TRINITY-thumbLarge.jpg",
          "format": "thumbLarge",
          "height": 150,
          "width": 150,
          "type": "image",
          "subtype": "photo",
          "caption": "<strong>Choir of Trinity Wall Street </strong> The ensemble performed on Sunday as part of Trinity Church&rsquo;s Lamentatio concert series in Lower Manhattan.",
          "copyright": "Tina Fineberg for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12TRINITY/12TRINITY-articleInline.jpg",
          "format": "Normal",
          "height": 127,
          "width": 190,
          "type": "image",
          "subtype": "photo",
          "caption": "<strong>Choir of Trinity Wall Street </strong> The ensemble performed on Sunday as part of Trinity Church&rsquo;s Lamentatio concert series in Lower Manhattan.",
          "copyright": "Tina Fineberg for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12TRINITY/12TRINITY-mediumThreeByTwo210.jpg",
          "format": "mediumThreeByTwo210",
          "height": 140,
          "width": 210,
          "type": "image",
          "subtype": "photo",
          "caption": "<strong>Choir of Trinity Wall Street </strong> The ensemble performed on Sunday as part of Trinity Church&rsquo;s Lamentatio concert series in Lower Manhattan.",
          "copyright": "Tina Fineberg for The New York Times"
        }
      ]
    },
    {
      "section": "Arts",
      "subsection": "Dance",
      "title": "Dancing With Doors and Amid Trash Cans",
      "abstract": "Daredevil vignettes devised by Brian Sanders for his company, Junk, rely heavily on props and precarious contraptions.",
      "url": "http://www.nytimes.com/2014/03/12/arts/dance/brian-sanderss-junk-infuses-choreography-with-props.html",
      "byline": "By SIOBHAN BURKE",
      "thumbnail_standard": "",
      "item_type": "Article",
      "source": "The New York Times",
      "updated_date": "2014-03-11T17:59:45-04:00",
      "created_date": "2014-03-11T17:59:46-04:00",
      "published_date": "2014-03-12T00:00:00-04:00",
      "material_type_facet": "Review",
      "kicker": "Dance Review",
      "subheadline": "",
      "des_facet": ["Dancing"],
      "org_facet": ["Junk"],
      "per_facet": ["Sanders, Brian"],
      "geo_facet": "",
      "related_urls": null,
      "multimedia": ""
    },
    {
      "section": "U.S.",
      "subsection": "",
      "title": "Classification Guide for Stellarwind Program",
      "abstract": "A guide to secrecy restrictions for Bush administration surveillance and data collection programs that operated outside FISA rules.",
      "url": "http://www.nytimes.com/interactive/2014/03/12/us/stellarwind-guidance-doc.html",
      "byline": "By CHARLIE SAVAGE",
      "thumbnail_standard": "",
      "item_type": "Interactive",
      "source": "The New York Times",
      "updated_date": "2014-03-11T17:58:52-04:00",
      "created_date": "2014-03-11T17:58:52-04:00",
      "published_date": "2014-03-12T00:00:00-04:00",
      "material_type_facet": "",
      "kicker": "",
      "subheadline": "",
      "des_facet": ["Foreign Intelligence Surveillance Act (FISA)", "Surveillance of Citizens by Government"],
      "org_facet": "",
      "per_facet": "",
      "geo_facet": "",
      "related_urls": null,
      "multimedia": ""
    },
    {
      "section": "Arts",
      "subsection": "Music",
      "title": "Traces of Lives, From Scores to Cigarettes",
      "abstract": "Carnegie Hall, in its Rose Museum, is hosting an exhibition of objects that relate to musical works being performed in the festival Vienna: City of Dreams.",
      "url": "http://www.nytimes.com/2014/03/12/arts/music/viennas-musical-giants-brings-artifacts-to-carnegie-hall.html",
      "byline": "By JAMES R. OESTREICH",
      "thumbnail_standard": "http://graphics8.nytimes.com/images/2014/03/12/arts/carnegie1/carnegie1-thumbStandard.jpg",
      "item_type": "Article",
      "source": "The New York Times",
      "updated_date": "2014-03-11T18:11:38-04:00",
      "created_date": "2014-03-11T17:56:55-04:00",
      "published_date": "2014-03-12T00:00:00-04:00",
      "material_type_facet": "News",
      "kicker": "Critic’s Notebook",
      "subheadline": "",
      "des_facet": ["Classical Music", "Musical Instruments"],
      "org_facet": ["Carnegie Hall", "Rose Museum"],
      "per_facet": "",
      "geo_facet": "",
      "related_urls": null,
      "multimedia": [
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/carnegie1/carnegie1-thumbStandard.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "Visitors at the exhibition, at the Rose Museum at Carnegie Hall.",
          "copyright": "Hiroyuki Ito for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/carnegie1/carnegie1-thumbLarge.jpg",
          "format": "thumbLarge",
          "height": 150,
          "width": 150,
          "type": "image",
          "subtype": "photo",
          "caption": "Visitors at the exhibition, at the Rose Museum at Carnegie Hall.",
          "copyright": "Hiroyuki Ito for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/carnegie1/carnegie1-articleInline.jpg",
          "format": "Normal",
          "height": 119,
          "width": 190,
          "type": "image",
          "subtype": "photo",
          "caption": "Visitors at the exhibition, at the Rose Museum at Carnegie Hall.",
          "copyright": "Hiroyuki Ito for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/carnegie1/carnegie1-mediumThreeByTwo210.jpg",
          "format": "mediumThreeByTwo210",
          "height": 140,
          "width": 210,
          "type": "image",
          "subtype": "photo",
          "caption": "Visitors at the exhibition, at the Rose Museum at Carnegie Hall.",
          "copyright": "Hiroyuki Ito for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12CARNEGIE/12CARNEGIE-thumbStandard.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "Beethoven&rsquo;s medicine spoon is on display at Carnegie Hall.",
          "copyright": "Hiroyuki Ito for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12CARNEGIE/12CARNEGIE-articleInline.jpg",
          "format": "Normal",
          "height": 40,
          "width": 190,
          "type": "image",
          "subtype": "photo",
          "caption": "Beethoven&rsquo;s medicine spoon is on display at Carnegie Hall.",
          "copyright": "Hiroyuki Ito for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12CARNEGIE/12CARNEGIE-thumbLarge.jpg",
          "format": "thumbLarge",
          "height": 150,
          "width": 150,
          "type": "image",
          "subtype": "photo",
          "caption": "Beethoven&rsquo;s medicine spoon is on display at Carnegie Hall.",
          "copyright": "Hiroyuki Ito for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12CARNEGIE/12CARNEGIE-mediumThreeByTwo210.jpg",
          "format": "mediumThreeByTwo210",
          "height": 140,
          "width": 210,
          "type": "image",
          "subtype": "photo",
          "caption": "Beethoven&rsquo;s medicine spoon is on display at Carnegie Hall.",
          "copyright": "Hiroyuki Ito for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/carnegie2/carnegie2-thumbStandard-v2.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "An autograph score from Mahler and a replica of his baton.",
          "copyright": "Hiroyuki Ito for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/carnegie2/carnegie2-thumbLarge-v2.jpg",
          "format": "thumbLarge",
          "height": 150,
          "width": 150,
          "type": "image",
          "subtype": "photo",
          "caption": "An autograph score from Mahler and a replica of his baton.",
          "copyright": "Hiroyuki Ito for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/carnegie2/carnegie2-articleInline.jpg",
          "format": "Normal",
          "height": 118,
          "width": 190,
          "type": "image",
          "subtype": "photo",
          "caption": "An autograph score from Mahler and a replica of his baton.",
          "copyright": "Hiroyuki Ito for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/carnegie2/carnegie2-mediumThreeByTwo210-v2.jpg",
          "format": "mediumThreeByTwo210",
          "height": 140,
          "width": 210,
          "type": "image",
          "subtype": "photo",
          "caption": "An autograph score from Mahler and a replica of his baton.",
          "copyright": "Hiroyuki Ito for The New York Times"
        }
      ]
    },
    {
      "section": "U.S.",
      "subsection": "",
      "title": "N.S.A. Timeline of Surveillance Law Developments",
      "abstract": "A chart, apparently from an internal National Security Agency presentation, lists milestones in surveillance rules over nearly four decades.",
      "url": "http://www.nytimes.com/interactive/2014/03/12/us/nsa-timeline.html",
      "byline": "By CHARLIE SAVAGE",
      "thumbnail_standard": "",
      "item_type": "Interactive",
      "source": "The New York Times",
      "updated_date": "2014-03-11T17:55:12-04:00",
      "created_date": "2014-03-11T17:55:13-04:00",
      "published_date": "2014-03-12T00:00:00-04:00",
      "material_type_facet": "",
      "kicker": "",
      "subheadline": "",
      "des_facet": ["Surveillance of Citizens by Government", "Foreign Intelligence Surveillance Act (FISA)"],
      "org_facet": ["National Security Agency"],
      "per_facet": "",
      "geo_facet": "",
      "related_urls": null,
      "multimedia": ""
    },
    {
      "section": "Arts",
      "subsection": "Art & Design",
      "title": "Park Avenue, the Art Gallery",
      "abstract": "The sculptures in Alice Aycock&#8217;s art installation &#8220;Park Avenue Paper Chase&#8221; are, as she had hoped, drawing attention.",
      "url": "http://www.nytimes.com/2014/03/12/arts/design/alice-aycocks-latest-installation-is-unveiled.html",
      "byline": "By TED LOOS",
      "thumbnail_standard": "http://graphics8.nytimes.com/images/2014/03/12/arts/12AYCOCK/12AYCOCK-thumbStandard-v2.jpg",
      "item_type": "Article",
      "source": "The New York Times",
      "updated_date": "2014-03-11T17:47:44-04:00",
      "created_date": "2014-03-11T17:47:46-04:00",
      "published_date": "2014-03-12T00:00:00-04:00",
      "material_type_facet": "News",
      "kicker": "",
      "subheadline": "",
      "des_facet": ["Art", "Sculpture"],
      "org_facet": ["Fund for Park Avenue"],
      "per_facet": ["Aycock, Alice"],
      "geo_facet": ["Park Avenue (Manhattan, NY)", "Manhattan (NYC)"],
      "related_urls": null,
      "multimedia": [
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12AYCOCK/12AYCOCK-thumbStandard-v2.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "&ldquo;Cyclone Twist,&rdquo; an Alice Aycock art installation, being assembled along Park Avenue.",
          "copyright": "Richard Perry/The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12AYCOCK/12AYCOCK-thumbLarge-v2.jpg",
          "format": "thumbLarge",
          "height": 150,
          "width": 150,
          "type": "image",
          "subtype": "photo",
          "caption": "&ldquo;Cyclone Twist,&rdquo; an Alice Aycock art installation, being assembled along Park Avenue.",
          "copyright": "Richard Perry/The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12AYCOCK/12AYCOCK-articleInline-v2.jpg",
          "format": "Normal",
          "height": 126,
          "width": 190,
          "type": "image",
          "subtype": "photo",
          "caption": "&ldquo;Cyclone Twist,&rdquo; an Alice Aycock art installation, being assembled along Park Avenue.",
          "copyright": "Richard Perry/The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12AYCOCK/12AYCOCK-mediumThreeByTwo210-v2.jpg",
          "format": "mediumThreeByTwo210",
          "height": 140,
          "width": 210,
          "type": "image",
          "subtype": "photo",
          "caption": "&ldquo;Cyclone Twist,&rdquo; an Alice Aycock art installation, being assembled along Park Avenue.",
          "copyright": "Richard Perry/The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12AYCOCKjp1/12AYCOCKjp1-thumbStandard.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "Alice Aycock's &ldquo;Maelstrom.\"",
          "copyright": "Richard Perry/The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12AYCOCKjp1/12AYCOCKjp1-thumbLarge.jpg",
          "format": "thumbLarge",
          "height": 150,
          "width": 150,
          "type": "image",
          "subtype": "photo",
          "caption": "Alice Aycock's &ldquo;Maelstrom.\"",
          "copyright": "Richard Perry/The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12AYCOCKjp1/12AYCOCKjp1-articleInline.jpg",
          "format": "Normal",
          "height": 127,
          "width": 190,
          "type": "image",
          "subtype": "photo",
          "caption": "Alice Aycock's &ldquo;Maelstrom.\"",
          "copyright": "Richard Perry/The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12AYCOCKjp1/12AYCOCKjp1-mediumThreeByTwo210.jpg",
          "format": "mediumThreeByTwo210",
          "height": 140,
          "width": 210,
          "type": "image",
          "subtype": "photo",
          "caption": "Alice Aycock's &ldquo;Maelstrom.\"",
          "copyright": "Richard Perry/The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12AYCOCKjp2/12AYCOCKjp2-thumbStandard.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "Alice Aycock's &ldquo;Hoop-La.\"",
          "copyright": "Richard Perry/The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12AYCOCKjp2/12AYCOCKjp2-thumbLarge.jpg",
          "format": "thumbLarge",
          "height": 150,
          "width": 150,
          "type": "image",
          "subtype": "photo",
          "caption": "Alice Aycock's &ldquo;Hoop-La.\"",
          "copyright": "Richard Perry/The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12AYCOCKjp2/12AYCOCKjp2-articleInline.jpg",
          "format": "Normal",
          "height": 127,
          "width": 190,
          "type": "image",
          "subtype": "photo",
          "caption": "Alice Aycock's &ldquo;Hoop-La.\"",
          "copyright": "Richard Perry/The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12AYCOCKjp2/12AYCOCKjp2-mediumThreeByTwo210.jpg",
          "format": "mediumThreeByTwo210",
          "height": 140,
          "width": 210,
          "type": "image",
          "subtype": "photo",
          "caption": "Alice Aycock's &ldquo;Hoop-La.\"",
          "copyright": "Richard Perry/The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12AYCOCKjp3/12AYCOCKjp3-thumbStandard.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "Alice Aycock's \"Cyclone Twist,\" part of &ldquo;Park Avenue Paper Chase.&rdquo;",
          "copyright": "Richard Perry/The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12AYCOCKjp3/12AYCOCKjp3-thumbLarge.jpg",
          "format": "thumbLarge",
          "height": 150,
          "width": 150,
          "type": "image",
          "subtype": "photo",
          "caption": "Alice Aycock's \"Cyclone Twist,\" part of &ldquo;Park Avenue Paper Chase.&rdquo;",
          "copyright": "Richard Perry/The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12AYCOCKjp3/12AYCOCKjp3-articleInline.jpg",
          "format": "Normal",
          "height": 127,
          "width": 190,
          "type": "image",
          "subtype": "photo",
          "caption": "Alice Aycock's \"Cyclone Twist,\" part of &ldquo;Park Avenue Paper Chase.&rdquo;",
          "copyright": "Richard Perry/The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12AYCOCKjp3/12AYCOCKjp3-mediumThreeByTwo210.jpg",
          "format": "mediumThreeByTwo210",
          "height": 140,
          "width": 210,
          "type": "image",
          "subtype": "photo",
          "caption": "Alice Aycock's \"Cyclone Twist,\" part of &ldquo;Park Avenue Paper Chase.&rdquo;",
          "copyright": "Richard Perry/The New York Times"
        }
      ]
    },
    {
      "section": "Arts",
      "subsection": "Music",
      "title": "The Voices of Montserrat",
      "abstract": "Europe’s oldest boys choir, the Escolania de Montserrat, has eased its residency requirements to raise enrollment. The move was effective and now they are on their first American tour.",
      "url": "http://www.nytimes.com/video/arts/music/100000002762324/the-voices-of-montserrat.html",
      "byline": "Braden Phillips",
      "thumbnail_standard": "",
      "item_type": "Video",
      "source": "The New York Times",
      "updated_date": "2014-03-11T17:55:23-04:00",
      "created_date": "2014-03-11T17:43:35-04:00",
      "published_date": "2014-03-11T00:00:00-04:00",
      "material_type_facet": "",
      "kicker": "",
      "subheadline": "",
      "des_facet": ["Classical Music"],
      "org_facet": "",
      "per_facet": "",
      "geo_facet": ["Catalonia (Spain)", "Spain"],
      "related_urls": null,
      "multimedia": [
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/11/multimedia/montserrat-choir/montserrat-choir-thumbStandard.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "",
          "caption": "",
          "copyright": ""
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/11/multimedia/montserrat-choir/montserrat-choir-thumbLarge.jpg",
          "format": "thumbLarge",
          "height": 150,
          "width": 150,
          "type": "image",
          "subtype": "",
          "caption": "",
          "copyright": ""
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/11/multimedia/montserrat-choir/montserrat-choir-articleInline.jpg",
          "format": "Normal",
          "height": 107,
          "width": 190,
          "type": "image",
          "subtype": "",
          "caption": "",
          "copyright": ""
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/11/multimedia/montserrat-choir/montserrat-choir-mediumThreeByTwo210.jpg",
          "format": "mediumThreeByTwo210",
          "height": 140,
          "width": 210,
          "type": "image",
          "subtype": "",
          "caption": "",
          "copyright": ""
        }
      ]
    },
    {
      "section": "Theater",
      "subsection": "",
      "title": "An Identity He Won’t Cede That Easily",
      "abstract": "The actor Armando Riesco reflects on his run, soon ending, as the war veteran Elliot Ortiz, a role he has played on and off since 2006 in a trilogy of plays by Quiara Alegr&#237;a Hudes.",
      "url": "http://www.nytimes.com/2014/03/12/theater/armando-riesco-reflects-on-his-role-in-the-elliot-trilogy.html",
      "byline": "By PATRICK HEALY",
      "thumbnail_standard": "http://graphics8.nytimes.com/images/2014/03/12/arts/12ARMANDO-inline/12ARMANDO-inline-thumbStandard.jpg",
      "item_type": "Article",
      "source": "The New York Times",
      "updated_date": "2014-03-11T17:42:43-04:00",
      "created_date": "2014-03-11T17:42:43-04:00",
      "published_date": "2014-03-12T00:00:00-04:00",
      "material_type_facet": "News",
      "kicker": "",
      "subheadline": "",
      "des_facet": ["Theater", "Actors and Actresses"],
      "org_facet": ["CBS Corporation|CBS|NYSE"],
      "per_facet": ["Riesco, Armando", "Hudes, Quiara Alegria"],
      "geo_facet": "",
      "related_urls": null,
      "multimedia": [
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12ARMANDO-inline/12ARMANDO-inline-thumbStandard.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "Armando Riesco, left, with Elliot Ruiz, the real-life inspiration for Mr. Riesco's character in the so-called Elliot Trilogy of plays by Quiara Alegr&iacute;a Hudes.",
          "copyright": "Steve Shevett"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12ARMANDO-inline/12ARMANDO-inline-thumbLarge.jpg",
          "format": "thumbLarge",
          "height": 150,
          "width": 150,
          "type": "image",
          "subtype": "photo",
          "caption": "Armando Riesco, left, with Elliot Ruiz, the real-life inspiration for Mr. Riesco's character in the so-called Elliot Trilogy of plays by Quiara Alegr&iacute;a Hudes.",
          "copyright": "Steve Shevett"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12ARMANDO-inline/12ARMANDO-inline-articleInline.jpg",
          "format": "Normal",
          "height": 126,
          "width": 190,
          "type": "image",
          "subtype": "photo",
          "caption": "Armando Riesco, left, with Elliot Ruiz, the real-life inspiration for Mr. Riesco's character in the so-called Elliot Trilogy of plays by Quiara Alegr&iacute;a Hudes.",
          "copyright": "Steve Shevett"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/arts/12ARMANDO-inline/12ARMANDO-inline-mediumThreeByTwo210.jpg",
          "format": "mediumThreeByTwo210",
          "height": 140,
          "width": 210,
          "type": "image",
          "subtype": "photo",
          "caption": "Armando Riesco, left, with Elliot Ruiz, the real-life inspiration for Mr. Riesco's character in the so-called Elliot Trilogy of plays by Quiara Alegr&iacute;a Hudes.",
          "copyright": "Steve Shevett"
        }
      ]
    },
    {
      "section": "Travel",
      "subsection": "",
      "title": "Hotel Discounts for Egencia Users",
      "abstract": "Egencia, the business travel brand of Expedia, is offering discounts to users who book through its new Trip Navigator application.",
      "url": "http://intransit.blogs.nytimes.com/2014/03/11/hotel-discounts-for-egencia-users/",
      "byline": "By RACHEL LEE HARRIS",
      "thumbnail_standard": "images/2014/03/11/travel/11egencia2/11egencia2-thumbStandard.jpg",
      "item_type": "Blog",
      "source": "The New York Times",
      "updated_date": "2014-03-11T17:28:22-04:00",
      "created_date": "2014-03-11T17:28:23-04:00",
      "published_date": "2014-03-11T00:00:00-04:00",
      "material_type_facet": "News",
      "kicker": "In Transit",
      "subheadline": "",
      "des_facet": ["Computers and the Internet", "Hotels and Travel Lodgings", "Travel and Vacations"],
      "org_facet": ["Apple Inc", "Expedia Inc"],
      "per_facet": "",
      "geo_facet": "",
      "related_urls": [
        {
          "suggested_link_text": "An Early Start for Cyber Deals",
          "url": "http://intransit.blogs.nytimes.com/2013/11/22/an-early-start-for-cyber-deals/"
        },
        {
          "suggested_link_text": "A London Hotel Has a Focus on Sustainability",
          "url": "http://intransit.blogs.nytimes.com/2014/03/07/a-london-hotel-has-a-focus-on-sustainability/"
        },
        {
          "suggested_link_text": "Park Hyatt Flagship Is Set for New York",
          "url": "http://intransit.blogs.nytimes.com/2014/03/04/park-hyatt-flagship-is-set-for-new-york/"
        },
        {
          "suggested_link_text": "In Miami Beach, a Concierge for Daytime Activities",
          "url": "http://intransit.blogs.nytimes.com/2014/02/28/in-miami-beach-a-concierge-for-daytime-activities/"
        },
        {
          "suggested_link_text": "New Butler Services Buff Luxury Hotels ",
          "url": "http://intransit.blogs.nytimes.com/2014/02/27/new-butler-services-buff-luxury-hotels/"
        }
      ],
      "blog_name": "In Transit",
      "multimedia": [
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/11/travel/11egencia2/11egencia2-thumbStandard.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "",
          "copyright": ""
        }
      ]
    },
    {
      "section": "Business Day",
      "subsection": "Media",
      "title": "Anne Sweeney, Top Disney TV Executive, Will Step Down",
      "abstract": "Ms. Sweeney, one of the most powerful women in television, will leave in 2015 after 18 years at the company.",
      "url": "http://www.nytimes.com/2014/03/12/business/media/anne-sweeney-top-disney-tv-executive-will-step-down.html",
      "byline": "By BROOKS BARNES and BILL CARTER",
      "thumbnail_standard": "",
      "item_type": "Article",
      "source": "The New York Times",
      "updated_date": "2014-03-11T17:49:21-04:00",
      "created_date": "2014-03-11T17:26:51-04:00",
      "published_date": "2014-03-12T00:00:00-04:00",
      "material_type_facet": "News",
      "kicker": "",
      "subheadline": "",
      "des_facet": ["Appointments and Executive Changes", "Television"],
      "org_facet": ["Walt Disney Company"],
      "per_facet": ["Sweeney, Anne"],
      "geo_facet": "",
      "related_urls": null,
      "multimedia": ""
    },
    {
      "section": "T:Style",
      "subsection": "",
      "title": "Q. and A. | Filmmaker Matt Wolf on the Origins of Teenage Culture ",
      "abstract": "The documentarian discusses his new project, a collage-like exploration of early-20th-century youth subcultures.",
      "url": "http://tmagazine.blogs.nytimes.com/2014/03/11/q-and-a-filmmaker-matt-wolf-on-the-origins-of-teenage-culture/",
      "byline": "By TIM MURPHY",
      "thumbnail_standard": "images/2014/03/11/t-magazine/11murphy-teenage/11murphy-teenage-thumbStandard.jpg",
      "item_type": "Blog",
      "source": "The New York Times",
      "updated_date": "2014-03-11T17:25:55-04:00",
      "created_date": "2014-03-11T17:25:56-04:00",
      "published_date": "2014-03-11T00:00:00-04:00",
      "material_type_facet": "News",
      "kicker": "T Magazine",
      "subheadline": "",
      "des_facet": ["Documentary Films and Programs"],
      "org_facet": "",
      "per_facet": "",
      "geo_facet": "",
      "related_urls": [
        {
          "suggested_link_text": "Now Screening ",
          "url": " Putting a Human Face on the African AIDS Epidemic "
        },
        { "suggested_link_text": "Now Screening ", "url": " The King of Modern Longboarding Looks Back " },
        { "suggested_link_text": "Now Screening ", "url": " Forty Years of Love and Art and Chaos " },
        { "suggested_link_text": "Site to Be Seen ", "url": " The PG Lives of X-Rated Stars" },
        { "suggested_link_text": "Now Showing ", "url": " 'The Source Family'" }
      ],
      "blog_name": "T Magazine",
      "multimedia": [
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/11/t-magazine/11murphy-teenage/11murphy-teenage-thumbStandard.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "",
          "copyright": ""
        }
      ]
    },
    {
      "section": "Business Day",
      "subsection": "Dealbook",
      "title": "Herbalife Shares Fall as Ackman Makes New Accusations",
      "abstract": "Shares in Herbalife were down slightly after William A. Ackman, the founder of the firm Pershing Square Capital Management, called Herbalife&#8217;s accounting of its Chinese business as &#8220;highly misleading.&#8221;",
      "url": "http://dealbook.nytimes.com/2014/03/11/herbalife-shares-fall-as-ackman-makes-new-accusations/",
      "byline": "By ALEXANDRA STEVENSON",
      "thumbnail_standard": "images/2014/03/12/business/dbpix-ackman/dbpix-ackman-thumbStandard.jpg",
      "item_type": "Blog",
      "source": "The New York Times",
      "updated_date": "2014-03-11T18:08:29-04:00",
      "created_date": "2014-03-11T17:17:29-04:00",
      "published_date": "2014-03-11T00:00:00-04:00",
      "material_type_facet": "News",
      "kicker": "DealBook",
      "subheadline": "",
      "des_facet": ["Diet and Nutrition", "Law and Legislation", "Regulation and Deregulation of Industry"],
      "org_facet": ["Herbalife Ltd", "Pershing Square Capital Management"],
      "per_facet": ["Ackman, William A"],
      "geo_facet": "",
      "related_urls": [
        {
          "suggested_link_text": "Senator Is Lobbying for Inquiry on Herbalife",
          "url": "http://dealbook.nytimes.com/2014/01/23/senator-calls-for-inquiry-into-herbalife/"
        },
        {
          "suggested_link_text": "Ackman, Herbalife and Celebrity Short-Sellers",
          "url": "http://dealbook.nytimes.com/2013/01/01/ackman-herbalife-and-celebrity-short-sellers/"
        }
      ],
      "blog_name": "DealBook",
      "multimedia": [
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/business/dbpix-ackman/dbpix-ackman-thumbStandard.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "",
          "copyright": ""
        }
      ]
    },
    {
      "section": "Sports",
      "subsection": "Olympics",
      "title": "Student (Russia) Beats Teacher (U.S.) in Sledge Hockey",
      "abstract": "The Russians, who decided five years ago to field a team for these Paralympics, and asked American coaches to help, beat the United States on Tuesday, a major victory for a young program.",
      "url": "http://www.nytimes.com/2014/03/12/sports/olympics/student-russia-beats-teacher-us-in-sledge-hockey.html",
      "byline": "By BEN SHPIGEL",
      "thumbnail_standard": "http://graphics8.nytimes.com/images/2014/03/12/sports/olympics/12paralympics1/12paralympics1-thumbStandard.jpg",
      "item_type": "Article",
      "source": "The New York Times",
      "updated_date": "2014-03-11T17:10:39-04:00",
      "created_date": "2014-03-11T17:09:15-04:00",
      "published_date": "2014-03-12T00:00:00-04:00",
      "material_type_facet": "News",
      "kicker": "",
      "subheadline": "",
      "des_facet": ["Sledge Hockey", "Paralympic Games"],
      "org_facet": "",
      "per_facet": "",
      "geo_facet": "",
      "related_urls": null,
      "multimedia": [
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/sports/olympics/12paralympics1/12paralympics1-thumbStandard.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "Rico Roman of the United States, left, and Ilia Volkov of Russia clashed on Tuesday.",
          "copyright": "James Hill for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/sports/olympics/12paralympics1/12paralympics1-thumbLarge.jpg",
          "format": "thumbLarge",
          "height": 150,
          "width": 150,
          "type": "image",
          "subtype": "photo",
          "caption": "Rico Roman of the United States, left, and Ilia Volkov of Russia clashed on Tuesday.",
          "copyright": "James Hill for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/sports/olympics/12paralympics1/12paralympics1-articleInline.jpg",
          "format": "Normal",
          "height": 126,
          "width": 190,
          "type": "image",
          "subtype": "photo",
          "caption": "Rico Roman of the United States, left, and Ilia Volkov of Russia clashed on Tuesday.",
          "copyright": "James Hill for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/sports/olympics/12paralympics1/12paralympics1-mediumThreeByTwo210.jpg",
          "format": "mediumThreeByTwo210",
          "height": 140,
          "width": 210,
          "type": "image",
          "subtype": "photo",
          "caption": "Rico Roman of the United States, left, and Ilia Volkov of Russia clashed on Tuesday.",
          "copyright": "James Hill for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/sports/12hockey1/12hockey1-thumbStandard.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "lia Volkov of Russia celebrated scoring Russia's first goal.",
          "copyright": "James Hill for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/sports/12hockey1/12hockey1-thumbLarge.jpg",
          "format": "thumbLarge",
          "height": 150,
          "width": 150,
          "type": "image",
          "subtype": "photo",
          "caption": "lia Volkov of Russia celebrated scoring Russia's first goal.",
          "copyright": "James Hill for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/sports/12hockey1/12hockey1-articleInline.jpg",
          "format": "Normal",
          "height": 126,
          "width": 190,
          "type": "image",
          "subtype": "photo",
          "caption": "lia Volkov of Russia celebrated scoring Russia's first goal.",
          "copyright": "James Hill for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/12/sports/12hockey1/12hockey1-mediumThreeByTwo210.jpg",
          "format": "mediumThreeByTwo210",
          "height": 140,
          "width": 210,
          "type": "image",
          "subtype": "photo",
          "caption": "lia Volkov of Russia celebrated scoring Russia's first goal.",
          "copyright": "James Hill for The New York Times"
        }
      ]
    },
    {
      "section": "Real Estate",
      "subsection": "",
      "title": "New Roots in Carroll Gardens",
      "abstract": "A Brooklyn neighborhood rich with brownstones and brick townhouses, and new zoning protects the urban-small-town atmosphere.",
      "url": "http://www.nytimes.com/2014/03/16/realestate/new-roots-in-carroll-gardens.html",
      "byline": "By JOHN FREEMAN GILL",
      "thumbnail_standard": "http://graphics8.nytimes.com/images/2014/03/16/realestate/SUB-16-Gaz1/SUB-16-Gaz1-thumbStandard.jpg",
      "item_type": "Article",
      "source": "The New York Times",
      "updated_date": "2014-03-11T17:08:58-04:00",
      "created_date": "2014-03-11T17:08:59-04:00",
      "published_date": "2014-03-16T00:00:00-04:00",
      "material_type_facet": "News",
      "kicker": "Living in",
      "subheadline": "",
      "des_facet": ["Real Estate and Housing (Residential)"],
      "org_facet": "",
      "per_facet": "",
      "geo_facet": ["Carroll Gardens (Brooklyn, NY)"],
      "related_urls": null,
      "multimedia": [
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/16/realestate/SUB-16-Gaz1/SUB-16-Gaz1-thumbStandard.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "<strong>292 Sackett Street</strong><br />A new five-bedroom five-and-a-half-bath two-family <a href=\"http://streeteasy.com/nyc/sale/856769-townhouse-292-sackett-street-carroll-gardens-brooklyn\" title=\"The listing.\">townhouse</a>, listed at $3.68 million.<br />(212) 732-0372",
          "copyright": "Katie Orlinsky for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/16/realestate/SUB-16-Gaz1/SUB-16-Gaz1-thumbLarge.jpg",
          "format": "thumbLarge",
          "height": 150,
          "width": 150,
          "type": "image",
          "subtype": "photo",
          "caption": "<strong>292 Sackett Street</strong><br />A new five-bedroom five-and-a-half-bath two-family <a href=\"http://streeteasy.com/nyc/sale/856769-townhouse-292-sackett-street-carroll-gardens-brooklyn\" title=\"The listing.\">townhouse</a>, listed at $3.68 million.<br />(212) 732-0372",
          "copyright": "Katie Orlinsky for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/16/realestate/SUB-16-Gaz1/SUB-16-Gaz1-articleInline.jpg",
          "format": "Normal",
          "height": 83,
          "width": 190,
          "type": "image",
          "subtype": "photo",
          "caption": "<strong>292 Sackett Street</strong><br />A new five-bedroom five-and-a-half-bath two-family <a href=\"http://streeteasy.com/nyc/sale/856769-townhouse-292-sackett-street-carroll-gardens-brooklyn\" title=\"The listing.\">townhouse</a>, listed at $3.68 million.<br />(212) 732-0372",
          "copyright": "Katie Orlinsky for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/16/realestate/SUB-16-Gaz1/SUB-16-Gaz1-mediumThreeByTwo210.jpg",
          "format": "mediumThreeByTwo210",
          "height": 140,
          "width": 210,
          "type": "image",
          "subtype": "photo",
          "caption": "<strong>292 Sackett Street</strong><br />A new five-bedroom five-and-a-half-bath two-family <a href=\"http://streeteasy.com/nyc/sale/856769-townhouse-292-sackett-street-carroll-gardens-brooklyn\" title=\"The listing.\">townhouse</a>, listed at $3.68 million.<br />(212) 732-0372",
          "copyright": "Katie Orlinsky for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/16/realestate/16-gaz1/16-gaz1-thumbStandard.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "<strong>154 President Street</strong><br />A two-family <a href=\"http://www.corcoran.com/nyc/Listings/Display/2912628\" title=\"The listing.\">brownstone</a> with central air-conditioning, listed at $2.99 million.<br />(718) 923-8027",
          "copyright": "Katie Orlinsky for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/16/realestate/16-gaz1/16-gaz1-thumbLarge.jpg",
          "format": "thumbLarge",
          "height": 150,
          "width": 150,
          "type": "image",
          "subtype": "photo",
          "caption": "<strong>154 President Street</strong><br />A two-family <a href=\"http://www.corcoran.com/nyc/Listings/Display/2912628\" title=\"The listing.\">brownstone</a> with central air-conditioning, listed at $2.99 million.<br />(718) 923-8027",
          "copyright": "Katie Orlinsky for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/16/realestate/16-gaz1/16-gaz1-articleInline.jpg",
          "format": "Normal",
          "height": 83,
          "width": 190,
          "type": "image",
          "subtype": "photo",
          "caption": "<strong>154 President Street</strong><br />A two-family <a href=\"http://www.corcoran.com/nyc/Listings/Display/2912628\" title=\"The listing.\">brownstone</a> with central air-conditioning, listed at $2.99 million.<br />(718) 923-8027",
          "copyright": "Katie Orlinsky for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/16/realestate/16-gaz1/16-gaz1-mediumThreeByTwo210.jpg",
          "format": "mediumThreeByTwo210",
          "height": 140,
          "width": 210,
          "type": "image",
          "subtype": "photo",
          "caption": "<strong>154 President Street</strong><br />A two-family <a href=\"http://www.corcoran.com/nyc/Listings/Display/2912628\" title=\"The listing.\">brownstone</a> with central air-conditioning, listed at $2.99 million.<br />(718) 923-8027",
          "copyright": "Katie Orlinsky for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/16/realestate/16-Gaz3/16-Gaz3-thumbStandard.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75,
          "type": "image",
          "subtype": "photo",
          "caption": "<strong>162 Huntington Street, #4R</strong><br />A two-bedroom two-and-a-half-bath duplex <a href=\"http://www.corcoran.com/nyc/Listings/Display/2770077\" title=\"The listing.\">condo</a> with a balcony, listed at $895,000.<br />(718) 422-2524",
          "copyright": "Katie Orlinsky for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/16/realestate/16-Gaz3/16-Gaz3-thumbLarge.jpg",
          "format": "thumbLarge",
          "height": 150,
          "width": 150,
          "type": "image",
          "subtype": "photo",
          "caption": "<strong>162 Huntington Street, #4R</strong><br />A two-bedroom two-and-a-half-bath duplex <a href=\"http://www.corcoran.com/nyc/Listings/Display/2770077\" title=\"The listing.\">condo</a> with a balcony, listed at $895,000.<br />(718) 422-2524",
          "copyright": "Katie Orlinsky for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/16/realestate/16-Gaz3/16-Gaz3-articleInline.jpg",
          "format": "Normal",
          "height": 83,
          "width": 190,
          "type": "image",
          "subtype": "photo",
          "caption": "<strong>162 Huntington Street, #4R</strong><br />A two-bedroom two-and-a-half-bath duplex <a href=\"http://www.corcoran.com/nyc/Listings/Display/2770077\" title=\"The listing.\">condo</a> with a balcony, listed at $895,000.<br />(718) 422-2524",
          "copyright": "Katie Orlinsky for The New York Times"
        },
        {
          "url": "http://graphics8.nytimes.com/images/2014/03/16/realestate/16-Gaz3/16-Gaz3-mediumThreeByTwo210.jpg",
          "format": "mediumThreeByTwo210",
          "height": 140,
          "width": 210,
          "type": "image",
          "subtype": "photo",
          "caption": "<strong>162 Huntington Street, #4R</strong><br />A two-bedroom two-and-a-half-bath duplex <a href=\"http://www.corcoran.com/nyc/Listings/Display/2770077\" title=\"The listing.\">condo</a> with a balcony, listed at $895,000.<br />(718) 422-2524",
          "copyright": "Katie Orlinsky for The New York Times"
        }
      ]
    }
  ]
}