{ name: 'NewsFeed',
  total: 0,
  watchKeywords:
   [ 'New York City',
     'Ford Flex',
     'Manhattan',
     'Brooklyn',
     'Scott P. Brown',
     'Decker',
     'Orient-Express Hotels',
     'Ukraine',
     'Belmond',
     'Russia',
     'Malaysian government',
     'Mayor Bill de Blasio',
     'East Harlem',
     'Ennio Morricone',
     'Tim Enthoven',
     'Alessandro Borgognone',
     'Ana Tijoux',
     'Raúl Arévalo',
     'NYT',
     'Massachusetts',
     'gold medal',
     'Vogue Italia',
     'New Jersey',
     'Bobby Flay',
     'Netherlands',
     'Bryant Park',
     'Facebook',
     'Amelia Island Concours',
     'Brooklyn Academy of Music',
     'Nigeria',
     'Tehran',
     'Benz',
     'Ford',
     'senator',
     'AMG',
     'ballot referendum',
     'Tunde Olaniran',
     'Warren E. Buffett',
     'Florida',
     'Tommy Mulvihill',
     'William Clay Ford',
     'Shaikh',
     'Shiffrin',
     'City Winery',
     'NoHo',
     'Williamsburg',
     'Xapo',
     'Internet',
     'Dmitry V. Firtash',
     'France' ],
  children:
   [ { name: 'New York City', size: 0 },
     { name: 'Ford Flex', size: 0 },
     { name: 'Manhattan', size: 0 },
     { name: 'Brooklyn', size: 0 },
     { name: 'Scott P. Brown', size: 0 },
     { name: 'Decker', size: 0 },
     { name: 'Orient-Express Hotels', size: 0 },
     { name: 'Ukraine', size: 0 },
     { name: 'Belmond', size: 0 },
     { name: 'Russia', size: 0 },
     { name: 'Malaysian government', size: 0 },
     { name: 'Mayor Bill de Blasio', size: 0 },
     { name: 'East Harlem', size: 0 },
     { name: 'Ennio Morricone', size: 0 },
     { name: 'Tim Enthoven', size: 0 },
     { name: 'Alessandro Borgognone', size: 0 },
     { name: 'Ana Tijoux', size: 0 },
     { name: 'Raúl Arévalo', size: 0 },
     { name: 'NYT', size: 0 },
     { name: 'Massachusetts', size: 0 },
     { name: 'gold medal', size: 0 },
     { name: 'Vogue Italia', size: 0 },
     { name: 'New Jersey', size: 0 },
     { name: 'Bobby Flay', size: 0 },
     { name: 'Netherlands', size: 0 },
     { name: 'Bryant Park', size: 0 },
     { name: 'Facebook', size: 0 },
     { name: 'Amelia Island Concours', size: 0 },
     { name: 'Brooklyn Academy of Music', size: 0 },
     { name: 'Nigeria', size: 0 },
     { name: 'Tehran', size: 0 },
     { name: 'Benz', size: 0 },
     { name: 'Ford', size: 0 },
     { name: 'senator', size: 0 },
     { name: 'AMG', size: 0 },
     { name: 'ballot referendum', size: 0 },
     { name: 'Tunde Olaniran', size: 0 },
     { name: 'Warren E. Buffett', size: 0 },
     { name: 'Florida', size: 0 },
     { name: 'Tommy Mulvihill', size: 0 },
     { name: 'William Clay Ford', size: 0 },
     { name: 'Shaikh', size: 0 },
     { name: 'Shiffrin', size: 0 },
     { name: 'City Winery', size: 0 },
     { name: 'NoHo', size: 0 },
     { name: 'Williamsburg', size: 0 },
     { name: 'Xapo', size: 0 },
     { name: 'Internet', size: 0 },
     { name: 'Dmitry V. Firtash', size: 0 },
     { name: 'France', size: 0 } ] }